### ISSUE TITLE
Issue with eQTL LD clumping

### ISSUE THREAD

**Issue by maxdudek** [hakha-most/gwas_eqtl#1]
Hi,

I'm trying to replicate the results of eQTL clumping in `eqtl_process/01_LD_clump_per_eGene.sh`. I'm not very familiar with using plink, so I'm trying to make sure the input file is formatted correctly.

However, in lines 75-85:

```{bash}
infile=$clumpdir/$gene".txt"
chr="`head -n 1 $infile | awk '{print $1}'`"
tempfile=$clumpdir/$gene".temp.txt"
echo "CHR GENE SNP P" > $tempfile
cat $infile >> $tempfile
mv $tempfile $infile

ldfile=$lddir/"chr"$chr
gwasfile=$clumpdir/$gene".txt"
outfile=$clumpdir/$gene
$plink --bfile $ldfile --clump $gwasfile --clump-p1 1 --clump-p2 1 --clump-r2 0.1 --clump-kb 1000 --out $outfile #using plink software
```

the file `$gwasfile` does not contain any data, and I'm unsure what the first chunk of code even does. I'm able to generate `$outdir/$tissue".v8.signif_variant_gene_pairs.hg19.txt"` just fine, and I'm guessing that if I filter for rows where the gene == $gene, I'll get what I want, but I'm not sure if that will play well with the rest of the code.

Could you clarify what this is trying to do and how to generate $gwasfile?

Thank you very much for your help!
Max

**Comment by hakha-most** [comment]
Hi, 

In lines 55-58, before the loop over genes, we generate a `.txt` file for each gene, such as `ENSG00000101019.txt`. 

Now, inside the loop (lines 75-80), we add a header to this file so that plink knows which column is which. This is the `$gwasfile`. Also, we extract the chromosome number, considering that LD reference is stored per chromosome.

Lines 82-85 run plink on this gene-level file and perform LD clumping.

Hope this helps!
Hakhamanesh

**Comment by maxdudek** [comment]
Ahh, thank you! I accidentally mixed up the directories and had the script writing the gene files elsewhere.
